In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('Datasett/Trafikkregistreringsdatasett/trafikkregistreringspunkt 1 - uke 42 og 43 2020.csv', sep=';')

In [4]:
data

,_id,_index,_score,_type,county_id,created_at_timestamp,datalogger_type,event_emitted_timestamp,event_number,event_timestamp,...,valid_classification,valid_event,valid_length,valid_speed,vehicle_type,vehicle_type_quality,vehicle_type_raw,weight,with_traffic_registration_point_direction,wrong_direction
0,1-27849732,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-26, 02:16:08.090",EMU,"2020-10-25, 23:59:53.564",27849732,"2020-10-25, 23:59:53.564",...,True,True,True,True,2.0,NaN,LMV2,0,False,False
1,1-27849731,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-26, 02:16:08.116",EMU,"2020-10-25, 23:58:28.296",27849731,"2020-10-25, 23:58:28.296",...,True,True,True,True,2.0,NaN,LMV2,0,True,False
2,1-27849730,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-26, 02:16:08.066",EMU,"2020-10-25, 23:58:25.527",27849730,"2020-10-25, 23:58:25.527",...,True,True,True,True,2.0,NaN,LMV2,0,True,False
3,1-27849729,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-26, 02:16:08.085",EMU,"2020-10-25, 23:58:19.077",27849729,"2020-10-25, 23:58:19.077",...,True,True,True,True,2.0,NaN,LMV2,0,True,False
4,1-27849728,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-26, 02:16:08.116",EMU,"2020-10-25, 23:57:49.695",27849728,"2020-10-25, 23:57:49.695",...,False,True,False,False,2.0,NaN,LMV2,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299772,1-27549743,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-12, 03:06:45.940",EMU,"2020-10-12, 00:02:36.830",27549743,"2020-10-12, 00:02:36.830",...,True,True,True,True,2.0,NaN,LMV2,0,False,False
299773,1-27549742,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-12, 03:06:45.939",EMU,"2020-10-12, 00:01:51.299",27549742,"2020-10-12, 00:01:51.299",...,True,True,True,True,2.0,NaN,LMV2,0,False,False
299774,1-27549741,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-12, 03:06:45.944",EMU,"2020-10-12, 00:01:35.216",27549741,"2020-10-12, 00:01:35.216",...,True,True,True,True,2.0,NaN,LMV2,0,True,False
299775,1-27549740,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-12, 03:06:45.947",EMU,"2020-10-12, 00:01:28.606",27549740,"2020-10-12, 00:01:28.606",...,True,True,True,True,2.0,NaN,LMV2,0,False,False
299776,1-27549739,traffic_event_vehicle_2020_10,NaN,traffic_event_vehicle,18,"2020-10-12, 03:06:45.940",EMU,"2020-10-12, 00:01:20.541",27549739,"2020-10-12, 00:01:20.541",...,True,True,True,True,2.0,NaN,LMV2,0,False,False

In [36]:
data.dtypes

_id                                           object
_index                                        object
created_at_timestamp                          object
event_emitted_timestamp                       object
event_number                                   int64
event_timestamp                               object
klokketime                                     int64
lane                                           int64
length                                       float64
qspeed                                       float64
region_id                                      int64
speed                                        float64
time_gap                                     float64
traffic_registration_point_id                  int64
valid_classification                            bool
valid_event                                     bool
valid_length                                    bool
valid_speed                                     bool
vehicle_type                                 float64
vehicle_type_quality                         float64
vehicle_type_raw                              object
weight                                         int64
with_traffic_registration_point_direction       bool
wrong_direction                                 bool
dtype: object

In [11]:
data['length'] = data['length'].map(lambda x: float(x.replace(',', '.')))

In [14]:
data['qspeed'] = data['qspeed'].map(lambda x: float(x.replace(',', '.')))

In [17]:
data['speed'] = data['speed'].map(lambda x: float(x.replace(',', '.')))

In [19]:
data['time_gap'] = data['time_gap'].map(lambda x: float(x.replace(',', '.')))

In [22]:
data['_score'].unique()

array([nan])

In [25]:
data.drop(columns=['_score'], inplace=True)

In [23]:
data['_type'].unique()

array(['traffic_event_vehicle'], dtype=object)

In [26]:
data.drop(columns=['_type'], inplace=True)

In [27]:
data['county_id'].unique()

array([18])

In [28]:
data.drop(columns=['county_id'], inplace=True)

In [29]:
data['datalogger_type'].unique()

array(['EMU'], dtype=object)

In [30]:
data.drop(columns=['datalogger_type'], inplace=True)

In [34]:
data['firmware_version'].unique()

array(['1.04 EMU3/15606'], dtype=object)

In [35]:
data.drop(columns=['firmware_version'], inplace=True)

In [43]:
data['_index'].unique()

array(['traffic_event_vehicle_2020_10'], dtype=object)

In [44]:
data.drop(columns=['_index'], inplace=True)

In [45]:
data.set_index('event_number')

,_id,created_at_timestamp,event_emitted_timestamp,event_timestamp,klokketime,lane,length,qspeed,region_id,speed,...,valid_classification,valid_event,valid_length,valid_speed,vehicle_type,vehicle_type_quality,vehicle_type_raw,weight,with_traffic_registration_point_direction,wrong_direction
event_number,,,,,,,,,,,,,,,,,,,,,
27849732,1-27849732,"2020-10-26, 02:16:08.090","2020-10-25, 23:59:53.564","2020-10-25, 23:59:53.564",23,4,4.5,0.0,1,73.2,...,True,True,True,True,2.0,NaN,LMV2,0,False,False
27849731,1-27849731,"2020-10-26, 02:16:08.116","2020-10-25, 23:58:28.296","2020-10-25, 23:58:28.296",23,3,4.6,0.0,1,75.4,...,True,True,True,True,2.0,NaN,LMV2,0,True,False
27849730,1-27849730,"2020-10-26, 02:16:08.066","2020-10-25, 23:58:25.527","2020-10-25, 23:58:25.527",23,3,4.6,0.0,1,80.1,...,True,True,True,True,2.0,NaN,LMV2,0,True,False
27849729,1-27849729,"2020-10-26, 02:16:08.085","2020-10-25, 23:58:19.077","2020-10-25, 23:58:19.077",23,3,4.1,0.0,1,75.4,...,True,True,True,True,2.0,NaN,LMV2,0,True,False
27849728,1-27849728,"2020-10-26, 02:16:08.116","2020-10-25, 23:57:49.695","2020-10-25, 23:57:49.695",23,4,4.3,2.3,1,75.4,...,False,True,False,False,2.0,NaN,LMV2,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27549743,1-27549743,"2020-10-12, 03:06:45.940","2020-10-12, 00:02:36.830","2020-10-12, 00:02:36.830",0,4,4.2,0.0,1,80.1,...,True,True,True,True,2.0,NaN,LMV2,0,False,False
27549742,1-27549742,"2020-10-12, 03:06:45.939","2020-10-12, 00:01:51.299","2020-10-12, 00:01:51.299",0,4,5.4,0.0,1,77.7,...,True,True,True,True,2.0,NaN,LMV2,0,False,False
27549741,1-27549741,"2020-10-12, 03:06:45.944","2020-10-12, 00:01:35.216","2020-10-12, 00:01:35.216",0,3,4.1,0.0,1,77.7,...,True,True,True,True,2.0,NaN,LMV2,0,True,False
27549740,1-27549740,"2020-10-12, 03:06:45.947","2020-10-12, 00:01:28.606","2020-10-12, 00:01:28.606",0,4,4.1,0.0,1,67.5,...,True,True,True,True,2.0,NaN,LMV2,0,False,False
27549739,1-27549739,"2020-10-12, 03:06:45.940","2020-10-12, 00:01:20.541","2020-10-12, 00:01:20.541",0,4,4.6,0.0,1,77.7,...,True,True,True,True,2.0,NaN,LMV2,0,False,False

In [46]:
data.drop(columns=['_id'], inplace=True)

In [63]:
data['vehicle_type'].fillna(None, inplace=True)

In [64]:
data['vehicle_type'] = data['vehicle_type'].astype('int64')

In [71]:
data.to_csv('./data/trafikkregistreringspunkt_1_-_uke_42_og_43_2020.csv', index=False)